#FSR Autogenerated Content. DO NOT DELETE
from .cpe_requests import cpe_requests
from .cve_requests_simple import cve_requests_simple
from .cve_requests import cve_requests
 
supported_operations = {'cpe_requests': cpe_requests, 'cve_requests_simple': cve_requests_simple, 'cve_requests': cve_requests, }